### ISSUE TITLE
Usability Forum (Internet Freedom in Africa)

### ISSUE THREAD

**Issue by luciewho** [Shoalsteed/I2P-Secure-Design-Collective#1]
[Usability Forum - Activity Findings.pdf](https://github.com/Shoalsteed/I2P-Usability-Lab/files/7289468/Usability.Forum.-.Activity.Findings.pdf)

**Comment by Shoalsteed** [comment]
My thoughts:

- someone mentioned wanting to own their data during one of the talks. I wondered what they meant. Technically that is not a thing that I would want. 
If I think about ownership in terms of communication and data, to me this means that it belongs to me. So, in this way, I2P does support ownership. It does not run on ads or data to sustain itself. It does not monetize.

-Looking at what people use, I see applications. At this stage I feel that I2P needs massive focus on its application layer if it truly wants adoption. These applications should stand-alone, and bundle a router. They should work cross platform, and participate in rigorous testing for usability and rely on existing standards for code, design, and marketability. 

-The idea of the "at risk user" is dated. Instead we should start with this: all people want something that is simple to use and that has a reputation ( ie my friends use it ). Focus on function, not philosophy. In my experience, most people who I know who actually do need to take care of how they communicate use trusted messaging apps and take calculated risk. They do not use Tor, they do not use I2P. 
Adoption is not just about presenting the option, it is about, in the case of I2P , putting I2P in something that is easy to use and provides a solution. So, efficiency, ease of use, and reputation. 

Our original work to create the questions https://github.com/Shoalsteed/UX/issues/30

my notes:
Privacy is personal information being accessed by other people
We should not reveal the source of information
We should OWN our information
For security we should own it 
Make obscurity a thing, limit the data you are creating
Encryption is a publicly non translatable language

**Comment by luciewho** [comment]
These are some research findings from the Forum that stood out to me:

What makes you decide to trust and use a tool?
Knowing how the tool is used, its usability, is it easy for people to use
Everyone or many people can use the tool, not limited to a small group. Can share info with others.
Consider feedback mechnism. Is it safe?
Finding out the source, who built this tool? Is that person credible.
Its efficiency, how does it work? Is it fast, does it back up your info?
"We have to be careful in the selection of tools that we use. Some tools we use alone. We need apps that every uses. What tools are used in Uganda? When developing a tool you need to consider all that."

What to do to ensure privacy and security?
Encrypt your messages, for electronic info.
Have different passwords on different accounts.
Do not use free wifi, Internet cafe. There are hackers.
Avoid click on links and prompts that are phishing scams.
When filling out account, do not put every bit of info about yourself on there.

**Comment by Shoalsteed** [comment]
_Finding out the source, who built this tool? Is that person credible._

This is one to think about. How do we provide credibility when as tool developers we may want to keep our names and faces off of the internet? How do people decide who is credible and who is not?

**Comment by Shoalsteed** [comment]
_Avoid click on links and prompts that are phishing scams_

If only Bote ( the very secure email option) was in better shape. It really offers so much protection from many things and the privacy that I think would really help.

**Comment by luciewho** [comment]
_For the community write-up_

Introduction about the Internet Freedom in Africa event. Usability forum with 10 journalists in Uganda.

**Goal:**
- Understand what establishes trust, their concept of privacy and what it means.
- Figure out what I2P is missing and what we can do better. How to better position I2P as a valuable tool.


**Findings**
_What makes you decide to trust and use a tool?_
- Knowing how the tool is used, its usability, is it easy for people to use
- Everyone or many people can use the tool, not limited to a small group. Can share info with others.
- Consider feedback mechnism. Is it safe?
- Finding out the source, who built this tool? Is that person credible.
- Its efficiency, how does it work? Is it fast, does it back up your info?
- "We have to be careful in the selection of tools that we use. Some tools we use alone. We need apps that everyone uses. What tools are used in Uganda? When developing a tool you need to consider all that."

_What to do to ensure privacy and security?_
- Encrypt your messages.
- Have different passwords on different accounts.
- Do not use free wifi, Internet cafe. There are hackers.
- Avoid clicking on links and prompts that are phishing scams.
- When filling out account, do not put every bit of info about yourself on there.

Add photos from workshop activity. 

**Insights**
_"Finding out the source, who built this tool? Is that person credible."_
This is one to think about. How do we provide credibility when as tool developers we may want to keep our names and faces off of the internet? How do people decide who is credible and who is not?

_"Avoid clicking on links and prompts that are phishing scams."_
If only Bote (the very secure email option) was in better shape. It really offers so much protection from many things and the privacy that I think would really help.

The idea of the "at risk user" is dated. Instead we should start with this: all people want something that is simple to use and that has a reputation ( ie my friends use it ). Focus on function, not philosophy. In my experience, most people who I know who actually do need to take care of how they communicate use trusted messaging apps and take calculated risk. They do not use Tor, they do not use I2P. Adoption is not just about presenting the option, it is about, in the case of I2P , putting I2P in something that is easy to use and provides a solution. So, efficiency, ease of use, and reputation.

Looking at what people use, I see applications. At this stage I feel that I2P needs massive focus on its application layer if it truly wants adoption. These applications should stand-alone, and bundle a router. They should work cross platform, and participate in rigorous testing for usability and rely on existing standards for code, design, and marketability.

**Comment by Shoalsteed** [comment]
Medium post https://i2p.medium.com/i2p-usability-lab-b2098bf27d4d
