### ISSUE TITLE
Classic macOS Installer 

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2P-Secure-Design-Collective#114]
### Download and Install Java.

![39](https://user-images.githubusercontent.com/50714166/215887480-a074e641-2f4e-4c76-9f68-985abfb570bb.png)
![40](https://user-images.githubusercontent.com/50714166/215887482-1caf6cc2-d676-4838-bb82-de66e36bf145.png)
![41](https://user-images.githubusercontent.com/50714166/215887484-5f84b366-95c6-4890-88fc-a16f991c6e75.png)
![42](https://user-images.githubusercontent.com/50714166/215887487-4b8e6f9e-656a-4293-9592-5062edc7ba6f.png)
![43](https://user-images.githubusercontent.com/50714166/215887489-89504fd3-a75f-4aa7-ada5-2749ec76b2cb.png)
![44](https://user-images.githubusercontent.com/50714166/215887490-09fc07e3-e450-4491-8253-b5f9cc8599fd.png)

**Comment by Shoalsteed** [comment]
### Install the I2P .jar 

![9](https://user-images.githubusercontent.com/50714166/215891137-ec779421-f6e4-41d3-85f6-daefacbedded.png)
![10](https://user-images.githubusercontent.com/50714166/215891139-6b00b218-226b-4a95-85d3-cd899c4b085c.png)
![11](https://user-images.githubusercontent.com/50714166/215891143-cb7d505c-3c31-4ad1-a1f4-be6793136110.png)
![12](https://user-images.githubusercontent.com/50714166/215891144-bf62f2cf-294b-4082-b18e-224704a0ef6e.png)
![13](https://user-images.githubusercontent.com/50714166/215891145-0a76a174-8808-438f-955a-b33a04d51b3d.png)
![14](https://user-images.githubusercontent.com/50714166/215891147-dc5bab94-122f-4d8f-a8ad-554fb535b717.png)
![15](https://user-images.githubusercontent.com/50714166/215891148-3ba95e29-f4c9-4930-aff1-498d38be3541.png)
![16](https://user-images.githubusercontent.com/50714166/215891150-20c18991-fbe5-450a-8747-fc6b643b9149.png)
![17](https://user-images.githubusercontent.com/50714166/215891151-b6fa2037-5ea8-46a0-be7d-a6d4e885888b.png)
![18](https://user-images.githubusercontent.com/50714166/215891153-ead58b4d-4d0d-4e19-8786-50f1ea73958b.png)
![19](https://user-images.githubusercontent.com/50714166/215891157-483cb75d-5057-4695-84ed-e036e428bd33.png)
![20](https://user-images.githubusercontent.com/50714166/215891158-d88e659e-ae79-4731-86f4-6add3f1959f6.png)
![21](https://user-images.githubusercontent.com/50714166/215891160-532c696a-0f39-4f52-af0b-581951d3ac20.png)

**Comment by Shoalsteed** [comment]
Find the I2P Folder in Applications
<img width="839" alt="Screen Shot 2023-01-31 at 3 58 16 PM" src="https://user-images.githubusercontent.com/50714166/215882353-e1eb1e6e-0f2e-4278-9263-352b51e80d91.png">

Open the folder and find the Start Router Icon shown.

<img width="778" alt="Screen Shot 2023-01-31 at 3 58 26 PM" src="https://user-images.githubusercontent.com/50714166/215882357-1d093257-fd57-479f-b722-c973c8126b66.png">

Click the icon to start the I2P router - it will show up in your dock as shown and you can choose too keep it there.

<img width="777" alt="Screen Shot 2023-01-31 at 3 58 42 PM" src="https://user-images.githubusercontent.com/50714166/215882359-4c0fc98f-6efb-442a-a44c-0fec1b6a7a86.png">

**Comment by Shoalsteed** [comment]
### Complete or Skip Set Up Wizard and Proceed to the Router Console

<img width="1046" alt="Screen Shot 2023-01-31 at 4 51 11 PM" src="https://user-images.githubusercontent.com/50714166/215891981-936a5801-26db-4f59-b89b-ff4696b89a62.png">
<img width="732" alt="Screen Shot 2023-01-31 at 4 51 23 PM" src="https://user-images.githubusercontent.com/50714166/215891983-71842d67-db54-46ad-accd-8d382fa807e7.png">
<img width="1051" alt="Screen Shot 2023-01-31 at 4 51 31 PM" src="https://user-images.githubusercontent.com/50714166/215891985-ff24d828-fcdf-49f5-af6c-0c3ae4b114bd.png">
<img width="1145" alt="Screen Shot 2023-01-31 at 4 51 43 PM" src="https://user-images.githubusercontent.com/50714166/215891986-ed29df6e-bac3-4f65-b191-d8ea45f3bf79.png">
<img width="870" alt="Screen Shot 2023-01-31 at 4 52 01 PM" src="https://user-images.githubusercontent.com/50714166/215891987-961d9d2d-3ffe-486f-9201-8efac9bdef75.png">
<img width="1046" alt="Screen Shot 2023-01-31 at 4 52 10 PM" src="https://user-images.githubusercontent.com/50714166/215891988-1ae2aeec-d814-4d8d-a938-69ce40530b99.png">
<img width="1061" alt="Screen Shot 2023-01-31 at 4 52 20 PM" src="https://user-images.githubusercontent.com/50714166/215891990-1a0cb93b-4256-4944-a667-d515c6d6d31d.png">

**Comment by eyedeekay** [comment]
Closable IMO

**Comment by Shoalsteed** [comment]
Implemented and closed!
