### ISSUE TITLE
/home sections

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2P-Secure-Design-Collective#131]
Graphs option - what OS it for? It does not work with MacOS.

**Comment by eyedeekay** [comment]
It should be for all OS's, please tell me about what error you see when on /graphs and I'll try to figure it out, it's probably a missing dependency thing.

**Comment by Shoalsteed** [comment]
closing issue: the message was that it did not work with macOS, but now it is displaying.
