### ISSUE TITLE
Dev Updates March

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2P-Secure-Design-Collective#132]
- Android
- MacOS
- DDoS
- Bugs

**Comment by eyedeekay** [comment]
Android had a 2.1.1 point release which was built from the I2P Java trunk at the time of the release, which was yesterday

MacOS update notarization process is ongoing

DDoS is ongoing but mitigations are flowing out to users

No bugs to report on at this time

**Comment by Shoalsteed** [comment]
Are there any bug fixes for Android 2.2.0 or in the point release?
I see : 
add newsfeed blocklist support
Android app 2.0.0 crashes whenever "long press to start I2P" is pressed

**Comment by eyedeekay** [comment]
2.0.0 crash is fixed, old news
Other known changes:
Fixed support for ports in i2ptunnel client destinations
Validate more kinds of address when adding hosts to the address book
Fix translations for stats on the home page
