### ISSUE TITLE
Application Testing 

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2P-Secure-Design-Collective#32]
In order to include as many different people in the process of testing, we need consider creating an easier way to test.
This should include more clear instructions for what files to download ( some people are not going to know the difference between arm64 or and or know that .su3 means what it means or how it will work with their I2P workflow if they have one at all. 

Even knowing how to install a file to the Plugins Manager is not clear. 
And this https://geti2p.net/en/docs/plugins page does not show a Mac workflow:
<img width="384" alt="Screen Shot 2022-02-15 at 4 59 33 PM" src="https://user-images.githubusercontent.com/50714166/154156695-7b1f90cb-00f9-4740-b822-2315be0680bd.png">
<img width="215" alt="Screen Shot 2022-02-15 at 4 59 43 PM" src="https://user-images.githubusercontent.com/50714166/154156696-c355f098-f1a1-4619-be98-45cfbd65cff3.png">

**Comment by Shoalsteed** [comment]
Is it an application or a plugin? Where is it important to distinguish and how do we provide that information in a simple way?

<img width="389" alt="Screen Shot 2022-02-15 at 5 08 38 PM" src="https://user-images.githubusercontent.com/50714166/154157824-66faf1dd-e58c-4434-ad4f-f6082193976a.png">

https://geti2p.net/en/docs/plugins

**Comment by eyedeekay** [comment]
> Is it an application or a plugin? Where is it important to distinguish and how do we provide that information in a simple way?
> 
> <img alt="Screen Shot 2022-02-15 at 5 08 38 PM" width="389" src="https://user-images.githubusercontent.com/50714166/154157824-66faf1dd-e58c-4434-ad4f-f6082193976a.png">
> 
> https://geti2p.net/en/docs/plugins

They are not different. Plugins are packaging for applications. They install applications, that's what they do.

**Comment by eyedeekay** [comment]
> In order to include as many different people in the process of testing, we need consider creating an easier way to test. This should include more clear instructions for what files to download ( some people are not going to know the difference between arm64 or and or know that .su3 means what it means or how it will work with their I2P workflow if they have one at all.
> 
> Even knowing how to install a file to the Plugins Manager is not clear. And this https://geti2p.net/en/docs/plugins page does not show a Mac workflow: <img alt="Screen Shot 2022-02-15 at 4 59 33 PM" width="384" src="https://user-images.githubusercontent.com/50714166/154156695-7b1f90cb-00f9-4740-b822-2315be0680bd.png"> <img alt="Screen Shot 2022-02-15 at 4 59 43 PM" width="215" src="https://user-images.githubusercontent.com/50714166/154156696-c355f098-f1a1-4619-be98-45cfbd65cff3.png">

Can't fix this until after release: https://i2pgit.org/i2p-hackers/i2p.i2p/-/issues/340 universal ShellService plugin packages can't happen until this is deployed. After that it won't matter, OS/ARCH detection will be possible.

There is no Mac workflow for plugins, they're managed by the I2P router and not OSX.

**Comment by Shoalsteed** [comment]
The workflow I mention has more to do with having screenshots or mention of where to find things/ show how they look on OSX when downloading and adding a plugin.

**Comment by Shoalsteed** [comment]
Why creating a more accessible onboarding for App testing is important:
- we are FOSS. We have limited resources. We cannot rely on having well resourced departments to create and implement consumer facing products. We need to create onboarding and docs that include not just devs, but designers, and people who will be interacting with the functionality of the tool in environments where we are not and therefore cannot anticipate factors that tech and design depend on to work best in creating safety and trust. This includes workflows that take into account stress or anxiety.

- lateral bias is hurting output. How can we create a usable tool if we can only rely on a a limited dataset for feedback? 

- Trust. When we do our best to include as many people in the process we can build not just with transparency, but with consensus and create trust modelling for people who may need to make use of the tool. If I cannot understand how it works, why should I trust it? How or why would I suggest a person to use it?

- consider naming files for OSX as OSX - not kernel name.
